name: Docker

on:
  workflow_call: #outro rotina que chama esta rotina

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #quer utilizar dados que esta no repositorio atualmente

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
          # Artifact name
          name: programa
          # Destination path
          path: main
      
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: lucaschagas550
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      uses: docker/build-push-action@v4.1.1
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: lucaschagas550/go_ci:${{github.ref_name}} # ref_name obtem o nome da branch
