name: Docker

on:
  workflow_call: #outro rotina que chama esta rotina

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #quer utilizar dados que esta no repositorio atualmente

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: lucaschagas550
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
