# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.20', '1.18', '>=1.20'] #Executa uma versao maior 1.20 se tiver,ou seja a mais nova disponivel, a 1.20 e 1.18
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version:  ${{ matrix.go_version }} 
      
      #criar qualquer imagem necessária no Docker Compose
    - name: Build-DB
      run: | 
        if [ "$TESTE" == "123" ]
        then
         echo teste: "$TESTE"
         echo "got our secret"
        fi
        echo git: "$TOKEN"
        echo test key: "$TESTE"
        docker-compose build
      env:
        TESTE: ${{ secrets.TESTE }}
        TOKEN: ${{ secrets.github_token }}
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v main.go
